### ISSUE TITLE
Is not possibile resize interface.

### ISSUE THREAD

**Issue by LucaNitti** [FarbstoffRSL/RSL-Helper#306] opened 2022-02-10 21:07 UTC
### Operating system

Windows 11

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

5.20

### Bug description

Not all interface is visible and there is no way to resize application windows.
Italian language
![Immagine 2022-02-10 220418](https://user-images.githubusercontent.com/10990055/153496287-1df5304c-5eea-4515-b88b-f498ec4f083f.png)

**Comment by OpaWattebausch** [comment] 2022-02-10 23:55
Scaling is not implemented in the helper. You can right click on the .exe --> properties --> compatibility --> change high DPI settings or change your windows scaling to 100%. Only solution right now.

**Comment by Chariot-Rider** [comment] 2022-02-11 00:26
Changing the scaling within windoze does not make a difference for me. Every tab is impacted.
![shard tracker](https://user-images.githubusercontent.com/93679093/153519425-ab7a8e0b-a2f3-42b5-a7c9-60fd49ac5ff2.png)
![settings tab](https://user-images.githubusercontent.com/93679093/153519476-3eec4fd8-687c-4b59-a18e-406242824006.png)
![event tracker](https://user-images.githubusercontent.com/93679093/153519515-948206b2-a319-460d-9a5d-2ee004ce737a.png)

**Comment by BlackHawk3000** [comment] 2022-02-11 04:02
#
Duplicate of #297

**Closed by BlackHawk3000** 2022-02-11 04:02 UTC
Labels: bug
