### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JohnS1987** [FarbstoffRSL/RSL-Helper#214] opened 2021-11-11 17:39 UTC
![Снимок экрана (3)](https://user-images.githubusercontent.com/94133586/141343639-7eeda474-6e3e-40d5-aa40-7434c1480646.png)

**Comment by sanasus** [comment] 2021-11-11 17:47
same problem(

**Comment by BlackHawk3000** [comment] 2021-11-11 17:49
Duplicate of #213

**Comment by poopswamp** [comment] 2021-11-11 20:26
same problem :(

**Comment by RoastDinners** [comment] 2021-11-11 21:27
i also have this problem. just needs an update, tho client has not been updated.

**Comment by XGH555** [comment] 2021-11-11 23:18
same problem

**Comment by Areeweblind** [comment] 2021-11-11 23:44
Same problem, even after updating the helper.

**Comment by BlackHawk3000** [comment] 2021-11-12 05:45
Update have fun

**Closed by BlackHawk3000** 2021-11-12 05:45 UTC
Labels: bug
