### ISSUE TITLE
RSL Helper completely unusable due to Updater "Not logged in." error

### ISSUE THREAD

**Issue by Nadis-Prime** [FarbstoffRSL/RSL-Helper#239] opened 2021-12-05 20:12 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v2.0.49.24

### PHP Version

Not sure

### Bug description

I have been completely unable to RSL Helper since the last update (when the "Not logged in" error began).  I found the suggested work around, which was to install the new version over the existing version and uncheck the automatically update check box at the end of the install.  THIS DOES NOT WORK.  Even after unchecking the box when I launch RSL Helper I see a message stating that there is a new version of the Updater available and it launches the updater anyway, I then get the Not logged in Error and of course can't get in. 

I love this product, but it is very frustrating (either due to how Plarium Play does their updates or how RSL Helper does theirs) that every time There is an update for Raid, RSL Helper dose not work for a day until an update is available.  Of course this has been by far the longest it has been broken for me.  

It appears that the "Not logged in." message is also appearing when you launch RSL Helper, but it flashes by quick.  (got a screen shot before it went away.

![RSL Helper](https://user-images.githubusercontent.com/95588960/144762247-84a840a2-5683-44a0-8bf7-31e3e30f2891.png)
.

### Steps to reproduce

Update then attempt to launch RSL Helper.

**Comment by kinthiri** [comment] 2021-12-05 21:43
Have the same issue, but keep in mind this product is developed by one person in their spare time. Everyone is aware the issue exists and there are steps being taken to resolve it. But at the present moment the defining factor is just hours available in a day. It will get sorted. Your best bet is to follow the appropriate channels on the Discord.

**Comment by smv1973** [comment] 2021-12-06 00:48
Chofly Elite has a little video about this on his YouTube channel 
https://www.youtube.com/watch?v=d-jwPups-hw&list=WL&index=2

And in the video (also he posted on the video site) he gives a site that that fixes the updater. It's a super easy, go watch the video & here is the site to get your fix for the Updater  

https://drive.google.com/u/0/uc?export=download&id=1Fi2GUiqpho9SYtx8M1Jie3x0G4-1f5Ti&pli=1

**Comment by flsgpn** [comment] 2021-12-06 08:59
The fix (and reason) for this issue is also available in this apps discord.

**Comment by BlackHawk3000** [comment] 2021-12-06 09:36
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-06 09:36 UTC
Labels: bug
