### ISSUE TITLE
not logged in

### ISSUE THREAD

**Issue by dnice120** [FarbstoffRSL/RSL-Helper#238] opened 2021-12-04 23:42 UTC
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

v.2.9.1.4

### PHP Version

php 8.0.7, build Jun 4 2021 01:50:04

### Bug description

![Screenshot (17)](https://user-images.githubusercontent.com/95550923/144727887-edd0ac4e-159c-4807-b4c3-3e87a4b6029e.png)

No matter what I do I keep getting a "not logged in" error code.

**Comment by L3xion** [comment] 2021-12-05 04:24
same

**Comment by hryCek10** [comment] 2021-12-05 09:39
same here :<

**Comment by Miky77ita** [comment] 2021-12-05 09:43
same here :<

**Comment by KRUZOVOD** [comment] 2021-12-05 10:39
и у меня эта проблема

**Comment by eskapist** [comment] 2021-12-05 17:23
Bei der ersten Installation den Hint vergessen und der Updater startete.
Fehlerbild dann wie hier beschrieben...
Setup nochmal drüber gebügelt und Haken entfernt.
Helper.exe startet trotzdem Update.

Kann das Tool aktuell also überhaupt nicht nutzen.

**Comment by unlucky-cat** [comment] 2021-12-05 18:06
please, stop develop your product - every time I need an autoclicker your solution is not working! Just stop to release new versions we dont need them, we need a working solution

**Comment by StephanCV** [comment] 2021-12-05 18:16
> please, stop develop your product - every time I need an autoclicker your solution is not working! Just stop to release new versions we dont need them, we need a working solution

If you had taken your time and went to the discord forum of this app you would have a working version! easy peasy as going there... mine is working perfect and have been doing so the past 48 hours!

**Comment by flsgpn** [comment] 2021-12-05 21:54
> please, stop develop your product - every time I need an autoclicker your solution is not working! Just stop to release new versions we dont need them, we need a working solution

So ungrateful.
Yes you do need a new version every time Raid makes an update, which has happened quite alot recently.
If all you need is an autoclicker, there are lots out there.

**Comment by Darkentik** [comment] 2021-12-06 09:24
Check this solution!
https://github.com/FarbstoffRSL/RSL-Helper/issues/239#issuecomment-986341959
It worked for me now.

> please, stop develop your product - every time I need an autoclicker your solution is not working! Just stop to release new versions we dont need them, we need a working solution

Stay patient! It is and will be a sparetime project. No one is foced to use it. The latest releases are more stable as the first versions. So stay calm and thanks Farbstoff for doing this tool or leave it behind and use a other tool.
But please do not troll here. Thanks.

**Comment by BlackHawk3000** [comment] 2021-12-06 09:36
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-06 09:36 UTC
Labels: bug
