### ISSUE TITLE
"outdated" version but no update is available

### ISSUE THREAD

**Issue by animejay** [FarbstoffRSL/RSL-Helper#137] opened 2021-09-08 14:54 UTC
**Bug describtion / Fehlerbeschreibung**

when i open the program, i get dialog box saying to wait for an updated version. then it closes but starts RAID.  There is no updated version when i check.

![Screenshot 2021-09-08 105202](https://user-images.githubusercontent.com/86800686/132533125-eca06759-b4c3-4568-8d9a-3020c058ccce.jpg)

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment] 2021-09-08 15:07
Duplicate of #135

**Closed by BlackHawk3000** 2021-09-08 15:07 UTC
Labels: bug
