### ISSUE TITLE
Shard tracking: epic does not count for leg counter

### ISSUE THREAD

**Issue by Selrache** [FarbstoffRSL/RSL-Helper#216] opened 2021-11-12 11:39 UTC
Hi,

I noticed during Void and Blue shard pull that the counter for leg pity shifts every time there is an epic.
Example:
![image](https://user-images.githubusercontent.com/94174217/141460904-657d6ef9-8411-499f-985d-f71dc7e08d8d.png)

After pull 10 blues shard: 8 rares and 2 epics, the count is 20 instead 22 for leg (12+10)
![image](https://user-images.githubusercontent.com/94174217/141461295-6366cb6d-558d-4970-bd23-317360c6ee23.png)

Same issue can be visible with void leg counter

**Comment by ToadJamb** [comment] 2021-11-12 21:35
I noticed this as well.

**Comment by n30hunt** [comment] 2021-12-01 18:20
I agree. This must be a bug.

**Comment by Blumbzy** [comment] 2021-12-01 19:07
No it's not a bug, epics doesn't count in pity. Only rares

**Comment by Dwza** [comment] 2022-01-10 08:10
this bug seems to be fixed. ill close this. if there is still a problem, comment here and i reopen it. or may open a new ticket

**Closed by Dwza** 2022-01-10 08:10 UTC
Labels: bug
