### ISSUE TITLE
Application says there is an update, and starts the updater, which gives error "you are not logged in"

### ISSUE THREAD

**Issue by Tyrranny** [FarbstoffRSL/RSL-Helper#234] opened 2021-12-02 22:34 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v.258

### PHP Version

Not sure

### Bug description

When I start the RSLHelper.exe program, it detects there is a patch, and opens the updater. When I click Update it starts then errors our with a dialog window saying "You are not logged in", just like after yesterday's patch. I tried uninstalling and installing the newest release, and it behaves the same.

### Steps to reproduce

Open RSLHelper.exe and click download on patcher.

### Relevant log output

```shell
**********************************************
Check if a Update available
CurrentVersion: 294924
Check if a new Updater available
Not logged in.

OnlineVersion: 21011
Update available
```

**Comment by fdi13** [comment] 2021-12-02 22:49
same

**Comment by Hahmer** [comment] 2021-12-03 00:21
Same here

**Comment by lingdoc** [comment] 2021-12-03 00:27
+1

**Comment by crush-you** [comment] 2021-12-03 00:32
I'm getting this even after installing the version from the Google drive link yesterday and unchecking "run updater" That worked for about 24 hours

**Comment by ztynzo** [comment] 2021-12-03 00:53
same -- is there an option to disable the update check at runtime?

**Comment by ADeitysGithub** [comment] 2021-12-03 01:26
Same, tried uninstalling and reinstalling and making sure "run updater" was unchecked and its still occuring.

**Comment by lingdoc** [comment] 2021-12-03 01:46
they're working on a fix to the updater, see: https://github.com/FarbstoffRSL/RSL-Helper/issues/229#issuecomment-985065748

in the meantime you can try blocking the updater application, as per: https://github.com/FarbstoffRSL/RSL-Helper/issues/229#issuecomment-985085304

**Comment by jmmallare** [comment] 2021-12-03 04:28
Try blocking the internet access of RSL Helper via your Firewall. It worked for me.

Credits to this guy for the fix:
https://github.com/FarbstoffRSL/RSL-Helper/issues/229#issuecomment-985082128

**Comment by marnux** [comment] 2021-12-03 08:09
I can confirm that setting the firewall rule, as suggested in #229, works. The RSLHelper.exe of the version mentioned in #229 otherwise keeps starting the updater and throwing the "Not logged in" error.

**Comment by ImNightShadow** [comment] 2021-12-03 10:23
![image](https://user-images.githubusercontent.com/39535458/144586894-1dad2739-dc3f-4a95-9022-b5d9d63aaac2.png)

**Comment by Cesc71** [comment] 2021-12-03 11:16
Same.
Is there a possibility to disable the autoupdate option without logging into the application?
for example through an .ini file or something similar.

**Comment by kamui86** [comment] 2021-12-03 13:34
same error as in the previous update " not logged in " and cant bypass it when run the helper

**Comment by SyFiDude** [comment] 2021-12-03 13:38
> mine opened the updater on its own after unchecking the box that tells it to update. still says not logged in

**Comment by kamui86** [comment] 2021-12-03 14:05
> > mine opened the updater on its own after unchecking the box that tells it to update. still says not logged in

what i wrote is when i run already installed  helper it checks in start if there's update on and then opens update window, cant close it because its gonna close entire app and when trying to update it saying not logged in

**Comment by Venjur** [comment] 2021-12-03 16:09
And now, even with the firewall block on, it still gets into update window and progress stops there...

**Comment by M3PHI5TO** [comment] 2021-12-03 19:23
Fix it pls, it's 4 days that i can't use the programm, ''not logged in'' has destroyed balls.

**Comment by BlackHawk3000** [comment] 2021-12-03 20:20
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-03 20:21 UTC
Labels: bug
