### ISSUE TITLE
RSL Helper updater v1.51 not working

### ISSUE THREAD

**Issue by SyFiDude** [FarbstoffRSL/RSL-Helper#226] opened 2021-11-27 23:50 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

unknown raid 4.9

### PHP Version

unknown

### Bug description

Clicked on the rslhelper icon to launch raid and it started to check for an update, shut down and ran the updater. when i clicked on the updater to get the latest versio9n it gives an error " Die Verbindung wurde erfolgreich geschlossen." .

now it wont update without giving that error.

### Steps to reproduce

does it every time i launch rsl helper.

### Relevant log output

```shell
.
```

**Comment by BlackHawk3000** [comment] 2021-11-29 15:26
Try using another internet connection or VPN

**Comment by gsantostasi** [comment] 2021-11-29 16:30
Same problem. I reported this problem before and many people had it. Previously it was solved by downloading some version of Visual Studio but the problem came back after the new update.

**Comment by gsantostasi** [comment] 2021-11-29 16:35
> Try using another internet connection or VPN

Why this is relevant?

**Comment by gsantostasi** [comment] 2021-11-29 16:54
Tried to use VPN, same problem. Access Denied.

**Comment by BlackHawk3000** [comment] 2021-11-29 21:10
Then try another internet connection for example the hotspot from your smartphone. 
The provider or your router is blocking something. so the updater cant work correct.

**Comment by Mexolius** [comment] 2021-12-01 18:13
I'll add my message cause it doesn't seem to have been provided yet.
![image](https://user-images.githubusercontent.com/39342674/144289842-bdffa21e-501f-448e-a06f-fe4ca3093bd1.png)

Windows 10 as well. It would be nice to have an option to uptade instead of having a forced uptater run every time a new minor version is released. It would prevent this kind of behaviour where everything seems to be working fine untill you try to download some bugfixes that weren't affecting you.

**Comment by swb64** [comment] 2021-12-01 19:26
Have the same problem, but mine says not logged in
![RSL](https://user-images.githubusercontent.com/8365570/144300317-7c9b34df-3669-4f1d-a120-0d5011919315.JPG)
.

**Comment by SunnyHours** [comment] 2021-12-01 21:28
> Have the same problem, but mine says not logged in ![RSL](https://user-images.githubusercontent.com/8365570/144300317-7c9b34df-3669-4f1d-a120-0d5011919315.JPG) .

Same as You Bud...Same Message Too!

**Comment by caveman-99** [comment] 2021-12-01 21:55
same here

**Comment by BlackHawk3000** [comment] 2021-12-01 21:57
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-01 21:57 UTC
Labels: bug

**Comment by ranafoutz** [comment] 2021-12-02 06:06
> Have the same problem, but mine says not logged in ![RSL](https://user-images.githubusercontent.com/8365570/144300317-7c9b34df-3669-4f1d-a120-0d5011919315.JPG) .

same here
worked this weekend

**Comment by Myrkee** [comment] 2021-12-03 03:24
Same here and even downloaded the new version from yesterday. And also unchecked the box in the end of installation and deleted both rsl helper folders, but when opening RSL helper it opens Updater as the first thing...

**Comment by HarveyEV** [comment] 2021-12-03 10:31
same here.

**Comment by Darkentik** [comment] 2021-12-03 12:57
same here

**Comment by davidopheim** [comment] 2021-12-03 19:58
same here I error too someone let me know when there is a fix?

**Comment by InqEnzo** [comment] 2021-12-05 18:23
I have had this problem for over a week now. I love RSL Helper it make it possible for me to play this game that takes way too much of my time. I really hope they fix it soon. I have uninstalled it twice and it still will not work it tries to update 1st thing and can't its not a problem with internet provider as I am using a laptop and have tried from 3 different locations all on different providers.
