### ISSUE TITLE
Outdated Version?

### ISSUE THREAD

**Issue by rejimaru** [FarbstoffRSL/RSL-Helper#136] opened 2021-09-08 14:08 UTC
I just updated it 10 seconds ago.. 
![565](https://user-images.githubusercontent.com/84756759/132524952-1bebd55f-35b1-476e-9153-6e1291eedef6.PNG)

**Comment by BlackHawk3000** [comment] 2021-09-08 14:09
Duplicate of #135

**Closed by BlackHawk3000** 2021-09-08 14:09 UTC
