### ISSUE TITLE
Feature request/suggestion - search for champs by skills

### ISSUE THREAD

**Issue by elemeledutki** [FarbstoffRSL/RSL-Helper#98] opened 2021-08-05 22:47 UTC
I might have been looking wrong, but I couldn't find it enywhere: search for champions by the skill/skills needed..
Ie: you look for champs having both weaken and DEF down (or ATK down and strighten and something else) - you select appropeiate lists/checkboxes/whatever - and you got a list.
Limitation to certain affinity/faction would be even better enhancement!

What you think?

**Comment by BlackHawk3000** [comment] 2021-08-08 08:43
Duplicate of #25

**Closed by BlackHawk3000** 2021-08-08 08:43 UTC
