### ISSUE TITLE
Updater does not start, with the message Not Logged In

### ISSUE THREAD

**Issue by BranxuRaid** [FarbstoffRSL/RSL-Helper#237] opened 2021-12-03 22:36 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v4.90.0

### PHP Version

8.3

### Bug description

After installing the latest version of RSh helper, it is started with admin privileges. It starts the helper update that does not run because the message "not logged in" appears.
![image](https://user-images.githubusercontent.com/95507184/144681898-10ac9e61-b432-4f78-9f64-1c839552e964.png)

**Comment by Jhonjairogomeztorres** [comment] 2021-12-04 02:47
x2

**Comment by Areeweblind** [comment] 2021-12-04 04:26
x3

**Comment by Areeweblind** [comment] 2021-12-04 04:31
Even after downloading the newest .exe file I get the same error.  Glad to log in where ever needed, just need to know how to do it.

**Comment by WhiteSammy** [comment] 2021-12-04 04:36
READ THE COMMENT IN ALL CAPS ON THE LATEST RELEASE YOU DENSE WET FARTS

**Comment by ceolson2** [comment] 2021-12-04 06:21
I followed the instructions on the release:

Unchecked the box so that the updater wouldn't run.

Then the program starts, checks the release number and calls the updater (which gets the login error message as above)

Oh and by the way, the comments in the release are not in CAPS.

**Comment by Jakuza001** [comment] 2021-12-04 06:32
x4 Same story, i followed  the instructions, unchecked the the box, but the updater started.

**Comment by KarlohReevan** [comment] 2021-12-04 07:03
> I followed the instructions on the release:
> 
> Unchecked the box so that the updater wouldn't run.
> 
> Then the program starts, checks the release number and calls the updater (which gets the login error message as above)
> 
> Oh and by the way, the comments in the release are not in CAPS.

A workaround for this issue can be found on this post, the information is here, read last messages.
There are two, one "complicated" and another "simpliest".

[https://github.com/FarbstoffRSL/RSL-Helper/issues/229](url)

**Comment by GummyBird-Maker** [comment] 2021-12-04 07:21
> ### Operating system
> 
> Windows 10
> ### Systemlanguage
> 
> English (EN)
> ### Current Game-Version
> 
> v4.90.0
> ### PHP Version
> 
> 8.3
> ### Bug description
> 
> After installing the latest version of RSh helper, it is started with admin privileges. It starts the helper update that does not run because the message "not logged in" appears. ![image](https://user-images.githubusercontent.com/95507184/144681898-10ac9e61-b432-4f78-9f64-1c839552e964.png)
> ### Steps to reproduce
> 
> _No response_
> ### Relevant log output
> 
> _No response_

You need to block RSL from using the internet, just block it with firewall rule and its work.
Open run and write firewall.cpl
1.Go to Advanced settings.
2.Right click Outbound Rules >> New Rule
3.Choose the program >> Block the connection 
4. Run and enjoy.

**Comment by BlackHawk3000** [comment] 2021-12-04 08:11
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-04 08:11 UTC
Labels: bug
