### ISSUE TITLE
Auto Sell Setup - Can't Clear rarity once selected

### ISSUE THREAD

**Issue by Tyrranny** [FarbstoffRSL/RSL-Helper#233] opened 2021-12-02 17:34 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

4.90.0

### PHP Version

No idea

### Bug description

Once I set 4 star to common, I cannot clear it and there is no option for none. Closed and reopened the program but it persists. Tried turning off auto Sell as well.

Sorry if I'm just missing something, I am new.

### Steps to reproduce

Set 5 or 6 star items to sell on any rarity.

### Relevant log output

```shell
None
```

**Comment by BlackHawk3000** [comment] 2021-12-02 19:23
Duplicate of #205

**Closed by BlackHawk3000** 2021-12-02 19:23 UTC
Labels: bug
