### ISSUE TITLE
Auto Run Not Working

### ISSUE THREAD

**Issue by zoeyn2** [FarbstoffRSL/RSL-Helper#348] opened 2022-03-28 20:38 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

RSL Helper v3.1 (resinstalled after champion chase Krisk event)

### Bug description

Thank you for creating RSL helper.  Currently the auto run feature is not working in dungeons for me.  It works for 3 - 5 runs, but then unexpectedly it just stops.  I am using "run infinitely" "auto sell artifacts" and "auto refill" functions.  I am having this issue with all dungeons.  Thank you.

**Comment by Dwza** [comment] 2022-03-28 21:48
could you test this a bit better?
turn all things off (autosell and what ever you got active) and check if this still happens.

**Comment by WiseDragonGR** [comment] 2022-03-29 11:47
Same problem here in various runs, either simple dungeons or Arcane keep for example

**Comment by carbonisle** [comment] 2022-03-29 13:27
Experiencing a similar issue.  Release 2 Build 32.  FPS 60.
Running Spider (not running super raids)
I do have event tracker on
Occasionally, the battle will end and RSL Helper will continue to display "Info: wait for finished battle"
The spinner will continue to spin and RSL Helper believes itself to still be running, but its waiting to see the battle is finished, even though the battle is actually finished. 

A quick click of the "Play" button will resume activity and it will continue as expected until the next time it fails to pick up the "Battle is finished" flag

**Comment by anatoly-kireev** [comment] 2022-03-29 17:05
Same here. Release 2 Build 32. FPS 60
No using any switches, only Number Of Runs.
Helper reloads some random number of rounds and then stops. Could be restarted by hitting Run button again. The least number of runs was 2, the most - 18

**Comment by pphantom** [comment] 2022-03-29 19:29
same here Release 2 Build 32. FPS 60. turned off auto sell as I thought that was the issue but it was not.  I tired using "use effective resources" with no luck. The worst kind of bug as it works until it doesn't.

**Comment by zoeyn2** [comment] 2022-03-29 21:41
> could you test this a bit better? turn all things off (autosell and what ever you got active) and check if this still happens.

Hi.  Thanks for the suggestion.  I did as you asked and turned off everything except for the "run infinitely" and the auto play function will still stop working randomly as others mentioned.  The little circle thing keeps spinning but nothing is happening.  Thank you for checking into this.

**Comment by lowerqueenandy** [comment] 2022-03-30 03:07
I am also noticing this issue as well. It's been happening randomly after just a few runs and I am using the Target Event Points

**Comment by Escondido** [comment] 2022-03-30 04:30
Same issue with me when only selecting Multi Level XP and nothing else. It seems to randomly stop for no reason.  Record so far is after 38 runs.

**Comment by oliviersamson** [comment] 2022-03-30 04:52
Same here running campaign (1 lvl 60 and 3 food) with:
Next to Max HP
Run Effective Resources

AutoClicker settings are:
Waiting time after fight: 3s
General click wait time: 500 ms

**Comment by pphantom** [comment] 2022-03-30 12:16
its almost like it loses connection but it doesn't as you see there is still data sent back and forth. Are there any logs during running? I only see a start log. Please let me know if I can help debug.

**Comment by halphyRU** [comment] 2022-03-30 12:22
and where can I get work logs?

**Comment by halphyRU** [comment] 2022-03-30 12:23
> its almost like it loses connection but it doesn't as you see there is still data sent back and forth. Are there any logs during running? I only see a start log. Please let me know if I can help debug.

and where can I get work logs?

**Comment by pphantom** [comment] 2022-03-30 12:31
![RSL](https://user-images.githubusercontent.com/18285945/160834746-58a7aaec-75ea-4b71-a0d3-f03fcba9dc56.JPG)

So that is a screen grab on a stop. The bottom tag says run finished but the upper tag says waiting for run to finish.... that's where its hanging

**Comment by halphyRU** [comment] 2022-03-30 12:45
how to fix it?

**Comment by Maghestriuss** [comment] 2022-03-30 13:01
same problem, on 3 different machines, it runs, untill it stops.. no messages, same as above picture. reinstall didnt work, update32 should have fixed it, but im running that, and its still stopping.

**Comment by mateiu2003k** [comment] 2022-03-30 15:12
I have the same problems mentioned above. It is still not fixed... I wonder if an older version could be a temporary solution.

**Comment by WiseDragonGR** [comment] 2022-03-30 16:25
Seems that the problem is RSLHelper does not recognize that a battle has ended so to trigger a new one, hence the message:
'Info: wait for finished battle'

**Comment by lindhsky** [comment] 2022-03-30 18:29
I have the same problem and I have tried a lot of different settings without the problem getting eliminated. FPS, the different options such as auto refill etc and also increased the delay after a battle. The problem described above in many posts is the same problem I have. 

BTW, what a program! Thank you so much!

**Comment by nikroma** [comment] 2022-03-30 20:23
I have the same problem. Tried different options. It stops on x run without visible reason.
![image](https://user-images.githubusercontent.com/13626524/160924343-1cd9d24c-da44-4d54-a349-dc28c633d01f.png)

**Comment by nikroma** [comment] 2022-03-30 23:51
I noticed that checkbox is getting unchecked as soon as the play has been pressed.
![image](https://user-images.githubusercontent.com/13626524/160949158-08278d73-e409-4a99-8936-1938d9f671b5.png)

**Comment by SofaKingTasty** [comment] 2022-03-31 02:56
Same exact issue. Will run for 5 or 6 runs on slower runs (5/6min runs)... 20-22 on quick 30 second spider runs, then just stop.

**Comment by TomateSoft** [comment] 2022-03-31 11:39
Hi, I'm getting the same issue.

Setup:
- I'm running Windows 11 with version 3.1, Rel. 2, Build 32.
- The issue happen with either Run Infinitely, Run Effective Ressource or Multi Level XP selected, everything else is default from the install.

How does the issue looks like:
- After a random amount of successful run the program stops replaying
- Everything is still responding in the interface and a run can be started by clicking play again.
- When the issue is triggered the log displays: **info: wait for finished battle - 1FarmerChamp(s)**

I haven't find any workaround for this, clicking on play from the victory/defeat screen being stuck will only trigger a single run, I have to go back to the champion selection for the stage and click play from there to get a new set of random run until the issue is triggered again.

**Comment by halphyRU** [comment] 2022-03-31 18:09
I wonder if they are dealing with the problem? I would like at least some official answer

**Comment by WiseDragonGR** [comment] 2022-04-01 13:07
Impressive that they can't fix this problem after so many days..

**Comment by anatoly-kireev** [comment] 2022-04-01 14:07
It seems the problem is fixed. I updated the tool using the Updater and it runs flawlessly.
Current build is V3.1 - Release: 5 - Build: 52

**Comment by nikroma** [comment] 2022-04-01 15:02
![image](https://user-images.githubusercontent.com/13626524/161289974-2009c1ac-f3d3-43e8-9352-a5a3b4d3cc25.png)

**Comment by carbonisle** [comment] 2022-04-01 18:43
I want to second the comment about respect.  Oftentimes, this programs are written by one person, in their own free time, without any compensation or consideration.  As often as Plarium is updating their client, keeping this plugin up-to-date and running smoothly is imaginably time consuming.  I, for one, do not expect the developer to get it perfect 100% of the time OR to be on immediate standby all of the time.

THANK YOU to the developer for the continued time and effort you put into maintaining this tool.  You are very appreciated!

**Comment by Dwza** [comment] 2022-04-01 20:08
@halphyRU Even when not all posts are answered, farbstoff is fixing problems like this as fast as he can. and yes, hes developing alone. we (dev-team) taking care about testing everything, updating github, answering most questions, provide enhancements to farbstoff and so on... actually there is a lot to do :D most people forgett that this tool is for free even if some famous streamers tried to push farstoff in some kind of pay thing. this is farbstoffs baby and he really want to keep it for free. he think its fair enough when some people donate if they like the programm. :)

and @carbonisle thank you for such nice words. i will copy this and send it to farbstoff :)
since this error is obviously solved, ill close this issue.

**Closed by Dwza** 2022-04-01 20:08 UTC
Labels: bug, solved

**Comment by ZazaKumar** [comment] 2022-04-02 12:52
still problem
![image](https://user-images.githubusercontent.com/4714455/161384178-82ceee8d-9170-4f5f-aea1-6e7a20a4118c.png)
