### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by StoupaJ** [FarbstoffRSL/RSL-Helper#269] opened 2022-01-18 11:35 UTC
### Operating system

Windows 11

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

v5.10.1

### Bug description

Hi,

(Windows Czech language)

 - download V2.16 - Release 2 - Build 3
 - clear install
 - run with internet:
![01](https://user-images.githubusercontent.com/17909494/149929904-e94f8808-d0b4-488a-a431-067bc771f5df.jpg)

 - run without internet (block RslHelper.exe in Firewall):
![02](https://user-images.githubusercontent.com/17909494/149929931-c013e641-f441-4125-8ef6-f99a5bc37aa2.jpg)

 - start log is OK:
[StartLog.log](https://github.com/FarbstoffRSL/RSL-Helper/files/7888685/StartLog.log)

**Comment by Andrey1377** [comment] 2022-01-18 14:25
Same error

**Comment by RyanSMurphy** [comment] 2022-01-18 14:27
+1 same error

**Comment by StoupaJ** [comment] 2022-01-18 14:37
I was watching (RSL discord) that they were already working on it... (The culprit is today's new game version)

**Comment by Bladesorrow** [comment] 2022-01-18 14:58
Getting the same error, hopefully it is fixed soon

**Comment by Areeweblind** [comment] 2022-01-18 18:15
Same. Even with it saying v2.20 in the client.

**Comment by victorvasilica** [comment] 2022-01-18 19:04
Same here, redownloading rsl did not help

**Comment by flayser-hub** [comment] 2022-01-18 20:36
как скоро заработает?

**Comment by victorvasilica** [comment] 2022-01-18 21:01
Just got an update and so far it is working. Thanks!

**Comment by svtv** [comment] 2022-01-19 10:56
Only worked once. All other attempts to start are accompanied by the message:
`if this message longer as 10 sec , close the helper in the Taskmanager`
![image](https://user-images.githubusercontent.com/25752575/150116561-423e35e8-ba43-4da3-b01f-ae259d85e19f.png)

**Comment by kamui86** [comment] 2022-01-19 11:10
> Only worked once. All other attempts to start are accompanied by the message: `if this message longer as 10 sec , close the helper in the Taskmanager` ![image](https://user-images.githubusercontent.com/25752575/150116561-423e35e8-ba43-4da3-b01f-ae259d85e19f.png) Win10 19044.1466 x64 En

got the same issue, yet its been working yesterday ...

**Comment by StoupaJ** [comment] 2022-01-19 14:16
Hi,
It would like to follow the actual infos on Farbstoff Discord ;)
Here is a link to the actual version:
https://bit.ly/3KzHIRQ

 - download exe
 - replace the original exe with a new file
 - run exe

**Comment by Prince-Armstrong** [comment] 2022-01-19 14:53
ссылка недоступна

**Comment by BlackHawk3000** [comment] 2022-01-20 03:59
Duplicate of #272

**Closed by BlackHawk3000** 2022-01-20 03:59 UTC
Labels: bug
