### ISSUE TITLE
Current RSL Version Outdated

### ISSUE THREAD

**Issue by nick-richard** [FarbstoffRSL/RSL-Helper#141] opened 2021-09-13 16:25 UTC
**Bug describtion / Fehlerbeschreibung**
After starting RSL Helper a popup comes up that states Current RSL Version is outdated . Please wait until an update is available. Then closes the application when you click ok, even though I am on the latest version.

**HowTo Reproduce / Wie man es reproduziert**
Just log in and after 30 seconds it will popup and shutdown the client

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
Windows 10

**Game Info(please complete the following information):**
Latest Version

**Additional context / Weiterer Infos**
![image](https://user-images.githubusercontent.com/31261402/133121341-afdf1ad6-eb24-48fd-abf4-600bb5c1df5d.png)

**Comment by BlackHawk3000** [comment] 2021-09-13 16:44
Duplicate of #135

**Closed by BlackHawk3000** 2021-09-13 16:44 UTC
Labels: bug
