### ISSUE TITLE
not logged in

### ISSUE THREAD

**Issue by jav666** [FarbstoffRSL/RSL-Helper#230] opened 2021-12-01 19:49 UTC
### Operating system

Windows 10

### Systemlanguage

German (DE)

### Current Game-Version

v2

### PHP Version

what?

### Bug description

message: "not logged in"

### Steps to reproduce

start the helper

### Relevant log output

```shell
message: "not logged in"
```

**Comment by KirilRusev** [comment] 2021-12-01 19:55
Same here 
![image](https://user-images.githubusercontent.com/19993495/144304354-ea7f6ad7-8452-4937-8cf7-5a5f19c1bca0.png)

**Comment by Audioslave69** [comment] 2021-12-01 19:57
I am having the same exact issue. I appreciate the work that the Developer does for this program. Just wondering if anyone else has fixed this problem. thank you so much.

**Comment by RoastDinners** [comment] 2021-12-01 20:16
i also have this problem with RSLHelper.

**Comment by czeeb** [comment] 2021-12-01 20:17
Exactly same issue here.  RSL Helper is not usable right now because of this.

**Comment by ADeitysGithub** [comment] 2021-12-01 20:30
Same issue here, thanks for all your hard work developers!

**Comment by DATDUDEJR** [comment] 2021-12-01 20:36
im having the same issue

**Comment by BlackHawk3000** [comment] 2021-12-01 20:41
Duplicate of #229

**Closed by BlackHawk3000** 2021-12-01 20:41 UTC
Labels: bug
