### ISSUE TITLE
Operation Refused into memory access and BSOD

### ISSUE THREAD

**Issue by lanillo** [FarbstoffRSL/RSL-Helper#443] opened 2022-08-27 22:09 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.80

### RSL Helper Version

3.31.21687

### Bug description

I got a BSOD, went into the EventViewer to see what caused the crash and multiple instances of this log near the time of the blue screen. I could not check my RAM usage before it crashed, it seems to be something that is leaking until my PC crashed to out of memory issues. This is fairly new, happened twice already, usually happens when I leave Raid and RSL open farming something and I turn off my screens and come back to check on progress (usually 3 hours+ later).

I also ran the windows tool for memory check and it completed successfully and I don't have any other issues running other programs/tools.

Let me know if I can give more information
!

### Steps to reproduce

Leave RSL and Raid running for more than 3 hours. Problems happens usually when the game is in the run result view

### Relevant log output

```shell

Faulting application name: Raid.exe, version: 2020.3.31.21687, time stamp: 0x62309ff5
Faulting module name: rslhelper_v35.dll, version: 0.0.0.0, time stamp: 0x62fa7423
Exception code: 0xc0000005
Fault offset: 0x0000000000005cf2
Faulting process id: 0x46a0
Faulting application start time: 0x01d8b9c395e098e6
Faulting application path: C:\Users\<User>\AppData\Local\PlariumPlay\StandAloneApps\raid\274\Raid.exe
Faulting module path: C:\Program Files\RSL_Helper_X64\rslhelper_v35.dll
Report Id: 780e6862-cb67-4206-9026-49fd4567226a
Faulting package full name: 
Faulting package-relative application ID: 

The program RSLHelper.exe version 3.4.1.73 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 3ef4
 Start Time: 01d8b4f8906a51af
 Termination Time: 24
 Application Path: C:\Program Files\RSL_Helper_X64\RSLHelper.exe
 Report Id: 6d6d193c-b62a-40f0-a020-85b713f80360
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown
```

**Comment by OpaWattebausch** [comment] 2022-08-29 11:07
1. The version of the helper you're using is 3.4.1.73 not 3.31.21687
2. The issue is fixed in v 3.4.2.8 that comes shortly after, so you did not update
3. A new version is out since now so closed

**Closed as completed by OpaWattebausch** 2022-08-29 11:07 UTC
Labels: bug
