### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by KingYanz** [FarbstoffRSL/RSL-Helper#258] opened 2021-12-24 07:13 UTC
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.00

### PHP Version

???

### Bug description

![2021-12-23 13_18_22-RSL_Helper_X64](https://user-images.githubusercontent.com/96611239/147327951-28782963-ad56-4cfb-9b7a-fc4cf3cfff8c.jpg)

Idk what happen but i replace RSLgethelper.exe from latest update, and this issue pop-up..pls help

**Comment by Dwza** [comment] 2022-01-11 10:38
Are you still forcing any problems?

**Comment by BlackHawk3000** [comment] 2022-01-20 04:01
Duplicate of #272

**Closed by BlackHawk3000** 2022-01-20 04:01 UTC
Labels: bug

**Comment by KingYanz** [comment] 2022-01-25 09:58
it's working fine now, no problem with VPN anymore..tvm
ps:
i'm sorry for late respon, your email is inside my spam folder..😔

Pada tanggal Kam, 20 Jan 2022 pukul 11.02 BlackHawk3000 <
***@***.***> menulis:
